### ISSUE TITLE
can not login admin ui in http ip port

### ISSUE THREAD

**Issue by xialvjun** [picoHz/taxy#20]
since `http://vps_ip:46492` is not a secure enviroment,  it can not set cookie and login.

I need taxy to get https, but I need https to use taxy. ┑(￣Д ￣)┍

How about add a config file and set the vhost for the admin ui:

```yaml
admin_ui:
  enabled: true
  vhost: vps_ip.nip.io  # so we can access `https://vps_ip.nip.io`
```

**Comment by xialvjun** [comment]
Besides, it seems taxy can't proxy request to its own admin_ui.

I have use caddy get https cert, then disable its 80 port binding, and change https port to 464. Then in `https://taxy.vps_ip.nip.io:464` I tell taxy bind to 80 and 443, and proxy 80/443 with vhost `taxy.vps_ip.nip.io` to `http://localhost:46492`, of course cert is required again by taxy. Then I go to `https://taxy.vps_ip.nip.io` got `502 BadGateway`.

**Comment by xialvjun** [comment]
forgot to say. I was use docker with network_mode: host

```yaml
version: "3"
services:
  taxy:
    image: ghcr.io/picohz/taxy:latest
    container_name: taxy
    volumes:
      - taxy-config:/root/.config/taxy
    network_mode: host
    # ports:
    #   # Add ports here if you want to expose them to the host
    #   - 80:80
    #   - 443:443
    #   - 46492:46492 # Admin panel
    restart: unless-stopped

volumes:
  taxy-config:
```
